apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-deployment
  namespace: 2048-game
spec:
  selector:
    matchLabels:
      app: frontend
  replicas: 1
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
      - name: frontend
        image: 236126054502.dkr.ecr.ap-south-1.amazonaws.com/suraj-cicd:1
        imagePullPolicy: Always
        ports:
        - containerPort: 80
